
import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'


export default function Rootlayout({ children }){
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link href="/style.css" rel="stylesheet" />
                <link href="/responsive.css" rel="stylesheet" />
                <link href="/font-awesome.min.css" rel="stylesheet" />
            </Head>
            <Header color={"red"} />
                { children }
            <Footer/>
        </>
    )
}
